// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"cpx-backend/app/user/service/internal/biz"
	"cpx-backend/app/user/service/internal/conf"
	data2 "cpx-backend/app/user/service/internal/data"
	"cpx-backend/app/user/service/internal/server"
	"cpx-backend/app/user/service/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data2.NewDB(confData, logger)
	client := data2.NewRedis(confData, logger)
	dataData, cleanup, err := data2.NewData(logger, db, client)
	if err != nil {
		return nil, nil, err
	}
	retrieveRepo := data2.NewRetrieveRepo(dataData, logger)
	updateRepo := data2.NewUpdateRepo(dataData, logger)
	userUseCase := biz.NewUserUseCase(retrieveRepo, updateRepo, logger)
	userService := service.NewUserService(userUseCase)
	grpcServer := server.NewGRPCServer(confServer, userService, logger)
	app := newApp(logger, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
