// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"cpx-backend/app/product/sevice/internal/biz"
	"cpx-backend/app/product/sevice/internal/conf"
	data2 "cpx-backend/app/product/sevice/internal/data"
	"cpx-backend/app/product/sevice/internal/server"
	"cpx-backend/app/product/sevice/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data2.NewDB(confData, logger)
	client := data2.NewRedis(confData, logger)
	dataData, cleanup, err := data2.NewData(logger, db, client)
	if err != nil {
		return nil, nil, err
	}
	productRepo := data2.NewProductRepo(dataData, logger)
	productUseCase := biz.NewProductUseCase(productRepo, logger)
	productService := service.NewProductService(productUseCase)
	grpcServer := server.NewGRPCServer(confServer, productService, logger)
	app := newApp(logger, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
