// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"cpx-backend/app/mall/portal/internal/biz"
	"cpx-backend/app/mall/portal/internal/conf"
	"cpx-backend/app/mall/portal/internal/data"
	"cpx-backend/app/mall/portal/internal/server"
	"cpx-backend/app/mall/portal/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"go.opentelemetry.io/otel/sdk/trace"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, registry *conf.Registry, auth *conf.Auth, logger log.Logger, tracerProvider *trace.TracerProvider) (*kratos.App, func(), error) {
	discovery := data.NewDiscovery(registry)
	productClient := data.NewProductServiceClient(discovery)
	userClient := data.NewUserServiceClient(discovery)
	dataData, err := data.NewData(confData, logger, productClient, userClient)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	userUseCase := biz.NewUserUseCase(userRepo, auth, logger)
	productRepo := data.NewProductRepo(dataData, logger)
	productUseCase := biz.NewProductUseCase(productRepo, auth, logger)
	portalService := service.NewPortalService(userUseCase, productUseCase, logger)
	grpcServer := server.NewGRPCServer(confServer, portalService, logger)
	httpServer := server.NewHTTPServer(confServer, auth, portalService, tracerProvider, logger)
	registrar := server.NewRegistrar(registry)
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
	}, nil
}
