// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"cpx-backend/app/mall/portal/internal/biz"
	"cpx-backend/app/mall/portal/internal/conf"
	"cpx-backend/app/mall/portal/internal/data"
	"cpx-backend/app/mall/portal/internal/server"
	"cpx-backend/app/mall/portal/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, registry *conf.Registry, logger log.Logger) (*kratos.App, func(), error) {
	discovery := data.NewDiscovery(registry)
	portalClient := data.NewUserServiceClient(discovery)
	dataData, err := data.NewData(confData, logger, portalClient)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	userUseCase := biz.NewUserUseCase(userRepo, logger)
	portalService := service.NewPortalService(userUseCase)
	grpcServer := server.NewGRPCServer(confServer, portalService, logger)
	httpServer := server.NewHTTPServer(confServer, portalService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
	}, nil
}
